version: '2'

services:
      
  php:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ".:/var/www"
      - "~/.composer/cache:/root/.composer/cache"
    expose:
      - "9000"
    depends_on:
      - mysql

  nginx:
    image: nginx:1.12-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./Docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro"
    volumes_from:
      - php
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: mysqld --sql-mode=""
    environment:
      MYSQL_ROOT_PASSWORD: "mysql-docker-default"
      MYSQL_DATABASE: "app"
      MYSQL_USER: "db_user"
      MYSQL_PASSWORD: "db_pass"
